#pragma once

#define TXTCRYPT_VERSION_MAJOR 0
#define TXTCRYPT_VERSION_MINOR 1
#define TXTCRYPT_VERSION_PATCH 0
#define TXTCRYPT_VERSION "0.1.0"

#define TXTCRYPT_MAGIC "TXTCRYPT"
#define TXTCRYPT_FORMAT_VERSION 1
